project:
  type: website
  output-dir: docs

website:
  title: "CV Camilo"
  navbar:
    background: secondary
    left:
      - text: "Home"
        file: index.qmd
      - text: "Skills"
        file: skills.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Work Experience"
        file: work.qmd
      - text: "Publications"
        file: publications.qmd
#      - text: "Portfolio"
#        file: portfolio.qmd
  
#  sidebar: 
#    - title: "Portfolio"
#      style: "floating"
#      contents:
#        - text: "Welcome"
#          file: portfolio.qmd
#        - section: "Forest Growth Modeling"
#          contents:
#            - text: "- Optim for nls"
#              file: filePortfolio/OptimFunction/Optim.qmd
#            - text: "- Autocorrelated growth"
#              file: filePortfolio/AtucorrelatedGrowth.qmd
#        - section: "Spatial Analysis"
#          contents: 
#            - text: "- Point patterns modeling"
    
#    - title: "Publications"
#      contents:
#        - publications.qmd
    
  favicon: Images/favicon.png
  page-footer: 
    center: "Copyright 2023, Camilo Martínez"
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

