---
title: "Teaching"
---

## Lecturer - Statistics

+---------------+---------------------------------------------------------------------------------------------------+
| Organization  | Universidad Nacional de Colombia sede Medellín. Facultad de Ciencias. Departamento de Estadística |
+---------------+---------------------------------------------------------------------------------------------------+
| Dates         | Feb 2024 - May 2024                                                                               |
+---------------+---------------------------------------------------------------------------------------------------+

#### Functions:

-   Conducting classes for the bachelor course of Statistics I, including topics of descriptive statistics, discrete and continuous probability distributions, maximum likelihood estimators, confidence intervals, and hypothesis testing.

-   Providing academic guidance to students during the course.

-   Participation in course coordination meetings.

## Lecturer - Forest Growth Modeling

Classes in the Forest Growth Modeling module of the First Diploma in Forest Resource Economics, offered by FEDEMADERAS.

+--------------+--------------------------------------------------------------------------+
| Organization | Federación Nacional de Industriales de la Madera, FEDEMADERAS, Colombia. |
+--------------+--------------------------------------------------------------------------+
| Dates        | August 2023                                                              |
+--------------+--------------------------------------------------------------------------+

#### Functions:

-   Conducted classes on quantitative and statistical methods utilized in forest growth modeling, theory of organic growth and site index concepts.

-   Assisting students with questions.

## Teaching Assistant - Forest Growth

Provided (*ad honorem*) support in teaching activities for students in the undergraduate forest growth course, under the supervision of Professor Sergio Alonso Orrego Suaza.

+--------------+--------------------------------------------------------------------------------------------------------------------+
| Organization | Universidad Nacional de Colombia sede Medellín. Facultad de Ciencias Agrarias. Departamento de Ciencias Forestales |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| Dates        | March 2022 - June 2022\                                                                                            |
|              | February 2023 - June 2023                                                                                          |
+--------------+--------------------------------------------------------------------------------------------------------------------+

#### Functions:

-   Conducted classes on quantitative methods utilized in forest growth modeling.

-   Developed R scripts for growth models and nonlinear regression methods.

-   Tidying of forest growth databases.

## Guest Lecturer - Silviculture of Forest Plantations

Provided support in teaching activities for students in the undergraduate silviculture of forest plantations course, under the supervision of Professor Luis Fernando Osorio Vélez.

+--------------+--------------------------------------------------------------------------------------------------------------------+
| Organization | Universidad Nacional de Colombia sede Medellín. Facultad de Ciencias Agrarias. Departamento de Ciencias Forestales |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| Dates        | September 2022, March 2023                                                                                         |
+--------------+--------------------------------------------------------------------------------------------------------------------+

#### Functions:

-   Conducted classes on quantitative and statistical methods utilized in forest growth modeling, site index and productivity of forest plantations.

## Speaker - Forest Symposium

Presentation of my undergraduate Thesis *Modeling dominant height growth of teak plantations (Tectona grandis L.f.) using environmental covariates* at the Forest Symposium.

+--------------+--------------------------------------------------------------------------------------------------------------------+
| Organization | Universidad Nacional de Colombia sede Medellín. Facultad de Ciencias Agrarias. Departamento de Ciencias Forestales |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| Dates        | December 2022                                                                                                      |
+--------------+--------------------------------------------------------------------------------------------------------------------+
